// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AgentTrustLayerClientProgram;

impl AgentTrustLayerClientProgram {
    pub const ROUTE_ID_AGENT_TRUST_LAYER: u8 = 1;
}

impl sails_rs::client::Program for AgentTrustLayerClientProgram {}

pub trait AgentTrustLayerClient {
    type Env: sails_rs::client::GearEnv;
    fn agent_trust_layer(
        &self,
    ) -> sails_rs::client::Service<agent_trust_layer::AgentTrustLayerImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> AgentTrustLayerClient
    for sails_rs::client::Actor<AgentTrustLayerClientProgram, E>
{
    type Env = E;
    fn agent_trust_layer(
        &self,
    ) -> sails_rs::client::Service<agent_trust_layer::AgentTrustLayerImpl, Self::Env> {
        self.service(AgentTrustLayerClientProgram::ROUTE_ID_AGENT_TRUST_LAYER)
    }
}
pub trait AgentTrustLayerClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AgentTrustLayerClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> AgentTrustLayerClientCtors
    for sails_rs::client::Deployment<AgentTrustLayerClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AgentTrustLayerClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod agent_trust_layer {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Escrow {
        pub id: u64,
        pub client: ActorId,
        pub provider: ActorId,
        pub arbiter: ActorId,
        pub amount: u128,
        pub terms_hash: String,
        pub proof_uri: Option<String>,
        pub dispute_uri: Option<String>,
        pub ruling_uri: Option<String>,
        pub created_at: u32,
        pub deadline_block: u32,
        pub status: EscrowStatus,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum EscrowStatus {
        Funded,
        Active,
        WorkSubmitted,
        Disputed,
        Resolved,
        Cancelled,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ServicePassport {
        pub owner: ActorId,
        pub handle: String,
        pub metadata_uri: String,
        pub price: u128,
        pub sla_blocks: u32,
        pub tags: Vec<String>,
        pub updated_at: u32,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum TrustError {
        AlreadyRegistered,
        EscrowNotFound,
        InvalidAmount,
        InvalidCounterparty,
        InvalidDeadline,
        InvalidMetadata,
        InvalidRuling,
        InvalidState,
        NotArbiter,
        NotClient,
        NotParticipant,
        NotProvider,
        NoClaim,
        RegistryFull,
        StorageFull,
    }

    pub trait AgentTrustLayer {
        type Env: sails_rs::client::GearEnv;
        fn accept_escrow(
            &mut self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::AcceptEscrow, Self::Env>;
        fn approve_work(
            &mut self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApproveWork, Self::Env>;
        fn cancel_expired(
            &mut self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelExpired, Self::Env>;
        fn claimable(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::Claimable, Self::Env>;
        fn create_escrow(
            &mut self,
            provider: ActorId,
            arbiter: ActorId,
            terms_hash: String,
            deadline_block: u32,
        ) -> sails_rs::client::PendingCall<io::CreateEscrow, Self::Env>;
        fn get_escrow(
            &self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetEscrow, Self::Env>;
        fn get_service(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetService, Self::Env>;
        fn list_escrows(&self) -> sails_rs::client::PendingCall<io::ListEscrows, Self::Env>;
        fn list_services(&self) -> sails_rs::client::PendingCall<io::ListServices, Self::Env>;
        fn open_dispute(
            &mut self,
            escrow_id: u64,
            dispute_uri: String,
        ) -> sails_rs::client::PendingCall<io::OpenDispute, Self::Env>;
        fn register_service(
            &mut self,
            handle: String,
            metadata_uri: String,
            price: u128,
            sla_blocks: u32,
            tags: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::RegisterService, Self::Env>;
        fn resolve_dispute(
            &mut self,
            escrow_id: u64,
            provider_award: u128,
            client_award: u128,
            ruling_uri: String,
        ) -> sails_rs::client::PendingCall<io::ResolveDispute, Self::Env>;
        fn submit_work(
            &mut self,
            escrow_id: u64,
            proof_uri: String,
        ) -> sails_rs::client::PendingCall<io::SubmitWork, Self::Env>;
        fn withdraw_claim(&mut self)
        -> sails_rs::client::PendingCall<io::WithdrawClaim, Self::Env>;
    }

    pub struct AgentTrustLayerImpl;

    impl sails_rs::client::Identifiable for AgentTrustLayerImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([215, 209, 153, 164, 171, 46, 203, 126]);
    }

    impl<E: sails_rs::client::GearEnv> AgentTrustLayer
        for sails_rs::client::Service<AgentTrustLayerImpl, E>
    {
        type Env = E;
        fn accept_escrow(
            &mut self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::AcceptEscrow, Self::Env> {
            self.pending_call((escrow_id,))
        }
        fn approve_work(
            &mut self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApproveWork, Self::Env> {
            self.pending_call((escrow_id,))
        }
        fn cancel_expired(
            &mut self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelExpired, Self::Env> {
            self.pending_call((escrow_id,))
        }
        fn claimable(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::Claimable, Self::Env> {
            self.pending_call((owner,))
        }
        fn create_escrow(
            &mut self,
            provider: ActorId,
            arbiter: ActorId,
            terms_hash: String,
            deadline_block: u32,
        ) -> sails_rs::client::PendingCall<io::CreateEscrow, Self::Env> {
            self.pending_call((provider, arbiter, terms_hash, deadline_block))
        }
        fn get_escrow(
            &self,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetEscrow, Self::Env> {
            self.pending_call((escrow_id,))
        }
        fn get_service(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetService, Self::Env> {
            self.pending_call((owner,))
        }
        fn list_escrows(&self) -> sails_rs::client::PendingCall<io::ListEscrows, Self::Env> {
            self.pending_call(())
        }
        fn list_services(&self) -> sails_rs::client::PendingCall<io::ListServices, Self::Env> {
            self.pending_call(())
        }
        fn open_dispute(
            &mut self,
            escrow_id: u64,
            dispute_uri: String,
        ) -> sails_rs::client::PendingCall<io::OpenDispute, Self::Env> {
            self.pending_call((escrow_id, dispute_uri))
        }
        fn register_service(
            &mut self,
            handle: String,
            metadata_uri: String,
            price: u128,
            sla_blocks: u32,
            tags: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::RegisterService, Self::Env> {
            self.pending_call((handle, metadata_uri, price, sla_blocks, tags))
        }
        fn resolve_dispute(
            &mut self,
            escrow_id: u64,
            provider_award: u128,
            client_award: u128,
            ruling_uri: String,
        ) -> sails_rs::client::PendingCall<io::ResolveDispute, Self::Env> {
            self.pending_call((escrow_id, provider_award, client_award, ruling_uri))
        }
        fn submit_work(
            &mut self,
            escrow_id: u64,
            proof_uri: String,
        ) -> sails_rs::client::PendingCall<io::SubmitWork, Self::Env> {
            self.pending_call((escrow_id, proof_uri))
        }
        fn withdraw_claim(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::WithdrawClaim, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AcceptEscrow (escrow_id: u64) -> () | super::TrustError, 0, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ApproveWork (escrow_id: u64) -> () | super::TrustError, 1, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CancelExpired (escrow_id: u64) -> () | super::TrustError, 2, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Claimable (owner: ActorId) -> u128, 3, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CreateEscrow (provider: ActorId, arbiter: ActorId, terms_hash: String, deadline_block: u32) -> u64 | super::TrustError, 4, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetEscrow (escrow_id: u64) -> super::Option<super::Escrow, >, 5, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetService (owner: ActorId) -> super::Option<super::ServicePassport, >, 6, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListEscrows () -> Vec<super::Escrow>, 7, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListServices () -> Vec<super::ServicePassport>, 8, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(OpenDispute (escrow_id: u64, dispute_uri: String) -> () | super::TrustError, 9, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RegisterService (handle: String, metadata_uri: String, price: u128, sla_blocks: u32, tags: Vec<String>) -> () | super::TrustError, 10, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ResolveDispute (escrow_id: u64, provider_award: u128, client_award: u128, ruling_uri: String) -> () | super::TrustError, 11, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitWork (escrow_id: u64, proof_uri: String) -> () | super::TrustError, 12, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawClaim () -> u128, 13, <super::AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum AgentTrustLayerEvents {
            #[codec(index = 0)]
            ClaimWithdrawn { owner: ActorId, amount: u128 },
            #[codec(index = 1)]
            DisputeOpened { escrow_id: u64, opened_by: ActorId },
            #[codec(index = 2)]
            EscrowAccepted { escrow_id: u64, provider: ActorId },
            #[codec(index = 3)]
            EscrowCancelled { escrow_id: u64 },
            #[codec(index = 4)]
            EscrowCreated {
                escrow_id: u64,
                client: ActorId,
                provider: ActorId,
                arbiter: ActorId,
                amount: u128,
            },
            #[codec(index = 5)]
            EscrowResolved {
                escrow_id: u64,
                provider_award: u128,
                client_award: u128,
            },
            #[codec(index = 6)]
            ServiceRegistered { owner: ActorId, handle: String },
            #[codec(index = 7)]
            WorkSubmitted { escrow_id: u64, provider: ActorId },
        }

        impl AgentTrustLayerEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::ClaimWithdrawn { .. } => 0,
                    Self::DisputeOpened { .. } => 1,
                    Self::EscrowAccepted { .. } => 2,
                    Self::EscrowCancelled { .. } => 3,
                    Self::EscrowCreated { .. } => 4,
                    Self::EscrowResolved { .. } => 5,
                    Self::ServiceRegistered { .. } => 6,
                    Self::WorkSubmitted { .. } => 7,
                }
            }
        }

        impl sails_rs::client::Event for AgentTrustLayerEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AgentTrustLayerEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AgentTrustLayerImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AgentTrustLayerImpl {
            type Event = AgentTrustLayerEvents;
        }
    }
}
