// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct TrustMissionsClientProgram;

impl TrustMissionsClientProgram {
    pub const ROUTE_ID_TRUST_MISSIONS: u8 = 1;
}

impl sails_rs::client::Program for TrustMissionsClientProgram {}

pub trait TrustMissionsClient {
    type Env: sails_rs::client::GearEnv;
    fn trust_missions(
        &self,
    ) -> sails_rs::client::Service<trust_missions::TrustMissionsImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> TrustMissionsClient
    for sails_rs::client::Actor<TrustMissionsClientProgram, E>
{
    type Env = E;
    fn trust_missions(
        &self,
    ) -> sails_rs::client::Service<trust_missions::TrustMissionsImpl, Self::Env> {
        self.service(TrustMissionsClientProgram::ROUTE_ID_TRUST_MISSIONS)
    }
}
pub trait TrustMissionsClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<TrustMissionsClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> TrustMissionsClientCtors
    for sails_rs::client::Deployment<TrustMissionsClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<TrustMissionsClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod trust_missions {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Mission {
        pub id: u64,
        pub creator: ActorId,
        pub title: String,
        pub terms_uri: String,
        pub reward: u128,
        pub deadline_block: u32,
        pub tags: Vec<String>,
        pub applicants: Vec<ActorId>,
        pub assigned_provider: Option<ActorId>,
        pub escrow_id: Option<u64>,
        pub proof_uri: Option<String>,
        pub created_at: u32,
        pub status: MissionStatus,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum MissionError {
        InvalidAmount,
        InvalidDeadline,
        InvalidMetadata,
        InvalidState,
        MissionNotFound,
        NotCreator,
        NotProvider,
        StorageFull,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum MissionStatus {
        Open,
        Assigned,
        ProofSubmitted,
        Closed,
    }

    pub trait TrustMissions {
        type Env: sails_rs::client::GearEnv;
        fn apply_to_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApplyToMission, Self::Env>;
        fn assign_mission(
            &mut self,
            mission_id: u64,
            provider: ActorId,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::AssignMission, Self::Env>;
        fn close_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::CloseMission, Self::Env>;
        fn create_mission(
            &mut self,
            title: String,
            terms_uri: String,
            reward: u128,
            deadline_block: u32,
            tags: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::CreateMission, Self::Env>;
        fn get_mission(
            &self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetMission, Self::Env>;
        fn list_missions(&self) -> sails_rs::client::PendingCall<io::ListMissions, Self::Env>;
        fn submit_mission_proof(
            &mut self,
            mission_id: u64,
            proof_uri: String,
        ) -> sails_rs::client::PendingCall<io::SubmitMissionProof, Self::Env>;
    }

    pub struct TrustMissionsImpl;

    impl sails_rs::client::Identifiable for TrustMissionsImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([84, 17, 113, 25, 130, 252, 138, 132]);
    }

    impl<E: sails_rs::client::GearEnv> TrustMissions
        for sails_rs::client::Service<TrustMissionsImpl, E>
    {
        type Env = E;
        fn apply_to_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApplyToMission, Self::Env> {
            self.pending_call((mission_id,))
        }
        fn assign_mission(
            &mut self,
            mission_id: u64,
            provider: ActorId,
            escrow_id: u64,
        ) -> sails_rs::client::PendingCall<io::AssignMission, Self::Env> {
            self.pending_call((mission_id, provider, escrow_id))
        }
        fn close_mission(
            &mut self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::CloseMission, Self::Env> {
            self.pending_call((mission_id,))
        }
        fn create_mission(
            &mut self,
            title: String,
            terms_uri: String,
            reward: u128,
            deadline_block: u32,
            tags: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::CreateMission, Self::Env> {
            self.pending_call((title, terms_uri, reward, deadline_block, tags))
        }
        fn get_mission(
            &self,
            mission_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetMission, Self::Env> {
            self.pending_call((mission_id,))
        }
        fn list_missions(&self) -> sails_rs::client::PendingCall<io::ListMissions, Self::Env> {
            self.pending_call(())
        }
        fn submit_mission_proof(
            &mut self,
            mission_id: u64,
            proof_uri: String,
        ) -> sails_rs::client::PendingCall<io::SubmitMissionProof, Self::Env> {
            self.pending_call((mission_id, proof_uri))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ApplyToMission (mission_id: u64) -> () | super::MissionError, 0, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(AssignMission (mission_id: u64, provider: ActorId, escrow_id: u64) -> () | super::MissionError, 1, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CloseMission (mission_id: u64) -> () | super::MissionError, 2, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CreateMission (title: String, terms_uri: String, reward: u128, deadline_block: u32, tags: Vec<String>) -> u64 | super::MissionError, 3, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetMission (mission_id: u64) -> super::Option<super::Mission, >, 4, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListMissions () -> Vec<super::Mission>, 5, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitMissionProof (mission_id: u64, proof_uri: String) -> () | super::MissionError, 6, <super::TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum TrustMissionsEvents {
            #[codec(index = 0)]
            MissionApplied { mission_id: u64, provider: ActorId },
            #[codec(index = 1)]
            MissionAssigned {
                mission_id: u64,
                provider: ActorId,
                escrow_id: u64,
            },
            #[codec(index = 2)]
            MissionClosed { mission_id: u64 },
            #[codec(index = 3)]
            MissionCreated {
                mission_id: u64,
                creator: ActorId,
                reward: u128,
            },
            #[codec(index = 4)]
            MissionProofSubmitted { mission_id: u64, provider: ActorId },
        }

        impl TrustMissionsEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::MissionApplied { .. } => 0,
                    Self::MissionAssigned { .. } => 1,
                    Self::MissionClosed { .. } => 2,
                    Self::MissionCreated { .. } => 3,
                    Self::MissionProofSubmitted { .. } => 4,
                }
            }
        }

        impl sails_rs::client::Event for TrustMissionsEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for TrustMissionsEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <TrustMissionsImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for TrustMissionsImpl {
            type Event = TrustMissionsEvents;
        }
    }
}
