// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct TrustMarketplaceClientProgram;

impl TrustMarketplaceClientProgram {
    pub const ROUTE_ID_TRUST_MARKETPLACE: u8 = 1;
}

impl sails_rs::client::Program for TrustMarketplaceClientProgram {}

pub trait TrustMarketplaceClient {
    type Env: sails_rs::client::GearEnv;
    fn trust_marketplace(
        &self,
    ) -> sails_rs::client::Service<trust_marketplace::TrustMarketplaceImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> TrustMarketplaceClient
    for sails_rs::client::Actor<TrustMarketplaceClientProgram, E>
{
    type Env = E;
    fn trust_marketplace(
        &self,
    ) -> sails_rs::client::Service<trust_marketplace::TrustMarketplaceImpl, Self::Env> {
        self.service(TrustMarketplaceClientProgram::ROUTE_ID_TRUST_MARKETPLACE)
    }
}
pub trait TrustMarketplaceClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<TrustMarketplaceClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> TrustMarketplaceClientCtors
    for sails_rs::client::Deployment<TrustMarketplaceClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<TrustMarketplaceClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod trust_marketplace {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct HireIntent {
        pub id: u64,
        pub client: ActorId,
        pub provider: ActorId,
        pub terms_uri: String,
        pub reward: u128,
        pub deadline_block: u32,
        pub trust_layer_program: ActorId,
        pub created_at: u32,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum MarketplaceError {
        InvalidMetadata,
        InvalidAmount,
        InvalidDeadline,
        InvalidProvider,
        ProviderNotFound,
        StorageFull,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ProviderProfile {
        pub owner: ActorId,
        pub handle: String,
        pub metadata_uri: String,
        pub tags: Vec<String>,
        pub price: u128,
        pub trust_layer_program: ActorId,
        pub updated_at: u32,
    }

    pub trait TrustMarketplace {
        type Env: sails_rs::client::GearEnv;
        fn create_hire_intent(
            &mut self,
            provider: ActorId,
            terms_uri: String,
            reward: u128,
            deadline_block: u32,
        ) -> sails_rs::client::PendingCall<io::CreateHireIntent, Self::Env>;
        fn get_hire_intent(
            &self,
            intent_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetHireIntent, Self::Env>;
        fn get_provider(
            &self,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetProvider, Self::Env>;
        fn list_hire_intents(
            &self,
        ) -> sails_rs::client::PendingCall<io::ListHireIntents, Self::Env>;
        fn list_providers(&self) -> sails_rs::client::PendingCall<io::ListProviders, Self::Env>;
        fn register_provider(
            &mut self,
            handle: String,
            metadata_uri: String,
            tags: Vec<String>,
            price: u128,
            trust_layer_program: ActorId,
        ) -> sails_rs::client::PendingCall<io::RegisterProvider, Self::Env>;
    }

    pub struct TrustMarketplaceImpl;

    impl sails_rs::client::Identifiable for TrustMarketplaceImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([44, 182, 48, 142, 202, 187, 89, 220]);
    }

    impl<E: sails_rs::client::GearEnv> TrustMarketplace
        for sails_rs::client::Service<TrustMarketplaceImpl, E>
    {
        type Env = E;
        fn create_hire_intent(
            &mut self,
            provider: ActorId,
            terms_uri: String,
            reward: u128,
            deadline_block: u32,
        ) -> sails_rs::client::PendingCall<io::CreateHireIntent, Self::Env> {
            self.pending_call((provider, terms_uri, reward, deadline_block))
        }
        fn get_hire_intent(
            &self,
            intent_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetHireIntent, Self::Env> {
            self.pending_call((intent_id,))
        }
        fn get_provider(
            &self,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetProvider, Self::Env> {
            self.pending_call((provider,))
        }
        fn list_hire_intents(
            &self,
        ) -> sails_rs::client::PendingCall<io::ListHireIntents, Self::Env> {
            self.pending_call(())
        }
        fn list_providers(&self) -> sails_rs::client::PendingCall<io::ListProviders, Self::Env> {
            self.pending_call(())
        }
        fn register_provider(
            &mut self,
            handle: String,
            metadata_uri: String,
            tags: Vec<String>,
            price: u128,
            trust_layer_program: ActorId,
        ) -> sails_rs::client::PendingCall<io::RegisterProvider, Self::Env> {
            self.pending_call((handle, metadata_uri, tags, price, trust_layer_program))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CreateHireIntent (provider: ActorId, terms_uri: String, reward: u128, deadline_block: u32) -> u64 | super::MarketplaceError, 0, <super::TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetHireIntent (intent_id: u64) -> super::Option<super::HireIntent, >, 1, <super::TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetProvider (provider: ActorId) -> super::Option<super::ProviderProfile, >, 2, <super::TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListHireIntents () -> Vec<super::HireIntent>, 3, <super::TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListProviders () -> Vec<super::ProviderProfile>, 4, <super::TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RegisterProvider (handle: String, metadata_uri: String, tags: Vec<String>, price: u128, trust_layer_program: ActorId) -> () | super::MarketplaceError, 5, <super::TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum TrustMarketplaceEvents {
            #[codec(index = 0)]
            HireIntentCreated {
                intent_id: u64,
                client: ActorId,
                provider: ActorId,
                reward: u128,
            },
            #[codec(index = 1)]
            ProviderRegistered { provider: ActorId, handle: String },
        }

        impl TrustMarketplaceEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::HireIntentCreated { .. } => 0,
                    Self::ProviderRegistered { .. } => 1,
                }
            }
        }

        impl sails_rs::client::Event for TrustMarketplaceEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for TrustMarketplaceEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <TrustMarketplaceImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for TrustMarketplaceImpl {
            type Event = TrustMarketplaceEvents;
        }
    }
}
